# Generated by Django 5.0.4 on 2026-03-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyframe',
            name='emotion_fear',
        ),
        migrations.RemoveField(
            model_name='emergencyframe',
            name='emotion_pain',
        ),
        migrations.RemoveField(
            model_name='emergencyframe',
            name='emotion_panic',
        ),
        migrations.AddField(
            model_name='emergencyframe',
            name='emotion_afraid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emergencyframe',
            name='emotion_angry',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emergencyframe',
            name='emotion_disgust',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emergencyframe',
            name='emotion_happy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emergencyframe',
            name='emotion_neutral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emergencyframe',
            name='emotion_sad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emergencyframe',
            name='emotion_surprise',
            field=models.FloatField(default=0.0),
        ),
    ]
